---
require:
- rubocop/require_tools
- rubocop-performance
AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Include:
  - "**/*.rb"
  - "**/*file"
  - "**/*.gemspec"
  - "*/lib/assets/*Template"
  - "*/lib/assets/*TemplateAndroid"
  Exclude:
  - "**/lib/assets/custom_action_template.rb"
  - "./vendor/**/*"
  - "**/lib/assets/DefaultFastfileTemplate"
  - "**/lib/assets/MatchfileTemplate"
  - "**/spec/fixtures/broken_files/broken_file.rb"
  - "**/*.provisionprofile"

# Metrics - Allow larger values for fastlane plugins
Metrics/ClassLength:
  Max: 500
Metrics/PerceivedComplexity:
  Max: 20
Metrics/AbcSize:
  Max: 50
Metrics/MethodLength:
  Max: 50
Metrics/CyclomaticComplexity:
  Max: 20
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "example/**/*"
    - "lib/fastlane/plugin/translate/actions/translate_with_deepl.rb"  # Complex batch processing
Metrics/ParameterLists:
  Max: 6  # Allow 6 parameters for complex plugin actions

# Fastlane-specific exclusions
Require/MissingRequireStatement:
  Exclude:
  - "**/spec/**/*.rb"
  - "**/spec_helper.rb"
  - "**/Fastfile"
  - "**/*.gemspec"
  - "**/actions/**/*.rb"
  - "lib/fastlane/plugin/translate/actions/**/*.rb"
  - "lib/fastlane/plugin/translate/translation_progress.rb"

# Standard fastlane style
Style/Documentation:
  Enabled: false
Layout/LineLength:
  Max: 370
Style/GuardClause:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false

# Standard fastlane file names (don't require snake_case)
Naming/FileName:
  Exclude:
  - "**/Dangerfile"
  - "**/Brewfile"
  - "**/Gemfile"
  - "**/Podfile"
  - "**/Rakefile"
  - "**/Fastfile"
  - "**/Deliverfile"
  - "**/Snapfile"
  - "**/Pluginfile"
  - "**/*.gemspec"

# Allow development dependencies in gemspec for fastlane plugins
Gemspec/DevelopmentDependencies:
  Enabled: false

# Allow case-when statements for clarity 
Style/HashLikeCase:
  Enabled: false
